### ISSUE TITLE
Issue in installing package in vs code

### ISSUE THREAD

**Issue by JatinBandawar** [DonJayamanne/python-extension-pack#39]
Type: <b>Feature Request</b>

There is some issue in  installation of packages in vscode some packages are not able to install and it is giving problem in running code 

Extension version: 1.7.0
VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by DonJayamanne** [comment]
Thanks for filling this issue
I’m sorry, but I don’t understand the problem
Please can you share some screenshot or details of the errors you are seeing

**Comment by marketec** [comment]
Having the same issue;

2024-03-29 21:26:56.772 [error] end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found: Error: end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found,end of central directory record signature not found
    at c:\Users\marsar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:74849
    at Array.reduce (<anonymous>)
    at v (c:\Users\marsar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:74835)
    at X.L (c:\Users\marsar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:66557)
    at async X.I (c:\Users\marsar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:64570)
    at async X.installGalleryExtensions (c:\Users\marsar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:60386)
    at async X.installFromGallery (c:\Users\marsar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:59669)
2024-03-29 21:27:41.216 [error] Error: end of central directory record signature not found,end of central directory record signature not found
    at c:\Users\marsar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:74849
    at Array.reduce (<anonymous>)
    at v (c:\Users\marsar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:74835)
    at X.L (c:\Users\marsar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:66557)
    at async X.I (c:\Users\marsar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:64570)
    at async X.installGalleryExtensions (c:\Users\marsar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:60386)
    at async X.installFromGallery (c:\Users\marsar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:59669)
2024-03-29 21:27:41.293 [error] end of central directory record signature not found,end of central directory record signature not found: Error: end of central directory record signature not found,end of central directory record signature not found
    at c:\Users\marsar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:74849
    at Array.reduce (<anonymous>)
    at v (c:\Users\marsar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:74835)
    at X.L (c:\Users\marsar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:66557)
    at async X.I (c:\Users\marsar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:64570)
    at async X.installGalleryExtensions (c:\Users\marsar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:60386)
    at async X.installFromGallery (c:\Users\marsar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:102:59669)

**Comment by DonJayamanne** [comment]
Been over a month since information was requested
Closing as stale
